version: "3.8"

services:
  reddit-bot:
    build: .
    container_name: "reddit-bot"
    restart: unless-stopped
    environment:
      - API_URL=${API_URL}
      - API_TOKEN=${API_TOKEN}
      - API_DEBUG=${API_DEBUG}
